# Generated by Django 4.1.7 on 2023-03-16 16:47

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=image.models.image_file_path),
        ),
        migrations.AddField(
            model_name='tier',
            name='is_expiring_link_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tier',
            name='is_original_file_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tier',
            name='thumbnail_height',
            field=models.IntegerField(default=200),
        ),
    ]
