# Generated by Django 4.1.7 on 2023-03-17 14:20

import django.core.validators
from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_image_tier_is_expiring_link_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='thumbnail_height',
        ),
        migrations.AddField(
            model_name='image',
            name='image_thumb_1',
            field=models.ImageField(null=True, upload_to=image.models.image_file_path),
        ),
        migrations.AddField(
            model_name='image',
            name='image_thumb_2',
            field=models.ImageField(null=True, upload_to=image.models.image_file_path),
        ),
        migrations.AddField(
            model_name='tier',
            name='thumbnail_1_height',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='tier',
            name='thumbnail_2_height',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tier_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
