# Generated by Django 4.1.7 on 2023-03-18 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_rename_image_thumb_1_image_thumb_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb_image_2',
            field=models.ImageField(null=True, upload_to='uploads/images'),
        ),
        migrations.AddField(
            model_name='tier',
            name='thumbnail_height_2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb_image_1',
            field=models.ImageField(null=True, upload_to='uploads/images'),
        ),
    ]
