# Generated by Django 4.1.7 on 2023-03-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_image_thumb_image_2_tier_thumbnail_height_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='is_expiring_link_enabled',
        ),
    ]
